-- =====================================================
-- TYPES (enum replacement)
-- =====================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
CREATE TYPE user_role AS ENUM ('STUDENT', 'INSTRUCTOR', 'ADMIN');
END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'chat_role') THEN
CREATE TYPE chat_role AS ENUM ('USER', 'ASSISTANT');
END IF;
END $$;

-- =====================================================
-- USERS
-- =====================================================
CREATE TABLE IF NOT EXISTS users (
                                     id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     full_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(150) NOT NULL UNIQUE,
    role       user_role NOT NULL DEFAULT 'STUDENT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

-- =====================================================
-- COURSES
-- (MySQL script có UPDATE active -> nên tạo luôn cột active)
-- =====================================================
CREATE TABLE IF NOT EXISTS courses (
                                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       title         VARCHAR(200) NOT NULL,
    description   TEXT,
    price         NUMERIC(12,2) NOT NULL DEFAULT 0,
    instructor_id BIGINT NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_course_instructor
    FOREIGN KEY (instructor_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    );

-- =====================================================
-- LESSONS
-- =====================================================
CREATE TABLE IF NOT EXISTS lessons (
                                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       course_id    BIGINT NOT NULL,
                                       title        VARCHAR(200) NOT NULL,
    video_url    VARCHAR(255),
    lesson_order INT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_lesson_course
    FOREIGN KEY (course_id)
    REFERENCES courses(id)
    ON DELETE CASCADE
    );

-- =====================================================
-- ENROLLMENTS
-- =====================================================
CREATE TABLE IF NOT EXISTS enrollments (
                                           id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           user_id     BIGINT NOT NULL,
                                           course_id   BIGINT NOT NULL,
                                           enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_enroll_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE,
    CONSTRAINT fk_enroll_course
    FOREIGN KEY (course_id)
    REFERENCES courses(id)
    ON DELETE CASCADE,
    CONSTRAINT uq_enroll_user_course UNIQUE (user_id, course_id)
    );

-- =====================================================
-- REVIEWS
-- =====================================================
CREATE TABLE IF NOT EXISTS reviews (
                                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       user_id    BIGINT NOT NULL,
                                       course_id  BIGINT NOT NULL,
                                       rating     INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment    TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_review_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE,
    CONSTRAINT fk_review_course
    FOREIGN KEY (course_id)
    REFERENCES courses(id)
    ON DELETE CASCADE
    );

-- =====================================================
-- CHAT SESSIONS
-- (MySQL ON UPDATE -> PostgreSQL dùng trigger)
-- =====================================================
CREATE TABLE IF NOT EXISTS chat_sessions (
                                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             session_key VARCHAR(64) NOT NULL UNIQUE,
    user_id     BIGINT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_chat_sessions_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE SET NULL
    );

CREATE INDEX IF NOT EXISTS idx_chat_sessions_user ON chat_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_updated ON chat_sessions(updated_at);

-- Trigger function to update updated_at
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_chat_sessions_updated_at ON chat_sessions;
CREATE TRIGGER trg_chat_sessions_updated_at
    BEFORE UPDATE ON chat_sessions
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- =====================================================
-- CHAT MESSAGES
-- =====================================================
CREATE TABLE IF NOT EXISTS chat_messages (
                                             id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             session_id BIGINT NOT NULL,
                                             role       chat_role NOT NULL,
                                             content    TEXT NOT NULL,
                                             created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_chat_messages_session
    FOREIGN KEY (session_id) REFERENCES chat_sessions(id)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_chat_messages_session_time ON chat_messages(session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_chat_messages_role ON chat_messages(role);

-- =====================================================
-- SEED DATA
-- =====================================================
INSERT INTO users (full_name, email, role) VALUES
                                               ('Nguyễn Văn A', 'a@gmail.com', 'INSTRUCTOR'),
                                               ('Trần Văn B', 'b@gmail.com', 'STUDENT')
    ON CONFLICT (email) DO NOTHING;

-- Course 1
INSERT INTO courses (title, description, price, instructor_id, active)
SELECT 'MySQL Cơ Bản', 'Học MySQL từ zero', 499000, u.id, TRUE
FROM users u
WHERE u.email = 'a@gmail.com'
    ON CONFLICT DO NOTHING;

-- Lessons for course 1 (tìm course theo title)
INSERT INTO lessons (course_id, title, lesson_order)
SELECT c.id, x.title, x.lesson_order
FROM courses c
         JOIN (VALUES
                   ('Giới thiệu MySQL', 1),
                   ('Tạo database & table', 2)
) AS x(title, lesson_order) ON TRUE
WHERE c.title = 'MySQL Cơ Bản';

-- Enrollment + Review (user B enroll course MySQL Cơ Bản)
INSERT INTO enrollments (user_id, course_id)
SELECT u.id, c.id
FROM users u
         JOIN courses c ON c.title = 'MySQL Cơ Bản'
WHERE u.email = 'b@gmail.com'
    ON CONFLICT (user_id, course_id) DO NOTHING;

INSERT INTO reviews (user_id, course_id, rating, comment)
SELECT u.id, c.id, 5, 'Khóa học rất dễ hiểu'
FROM users u
         JOIN courses c ON c.title = 'MySQL Cơ Bản'
WHERE u.email = 'b@gmail.com'
    ON CONFLICT DO NOTHING;

-- Bulk courses (theo instructor a@gmail.com)
INSERT INTO courses (title, description, price, instructor_id, active)
SELECT x.title, x.description, x.price, u.id, TRUE
FROM users u
         JOIN (VALUES
                   ('MySQL Nâng Cao', 'Tối ưu truy vấn và index MySQL', 699000),
                   ('Spring Boot Cơ Bản', 'Xây dựng REST API với Spring Boot', 799000),
                   ('Spring Security', 'Bảo mật ứng dụng với Spring Security', 899000),
                   ('React Cơ Bản', 'Học React từ cơ bản đến thực hành', 599000),
                   ('React Nâng Cao', 'Hook, Performance và Best Practices', 799000),
                   ('Vue 3 + TypeScript', 'Xây dựng SPA với Vue 3 và TS', 699000),
                   ('Docker Cho Người Mới', 'Docker từ cơ bản đến triển khai', 649000),
                   ('DevOps Căn Bản', 'CI/CD với Docker và GitHub Actions', 899000),
                   ('Kotlin Backend', 'Xây dựng backend với Kotlin Spring', 799000),
                   ('System Design Cơ Bản', 'Thiết kế hệ thống cho developer', 999000)
) AS x(title, description, price) ON TRUE
WHERE u.email = 'a@gmail.com'
    ON CONFLICT DO NOTHING;

-- Nếu bạn muốn set một vài course inactive theo id như MySQL:
-- (Postgres id có thể khác vì identity, nên khuyên set inactive theo title thay vì id)
-- UPDATE courses SET active = FALSE WHERE title IN ('...', '...');
